apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name-deployment
  labels:
    app: app-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-name
  template:
    metadata:
      labels:
        app: app-name
    spec:
      containers:
        - name: app-name
          image: ahmedabduelkhaleq/app-name:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-name-service
spec:
  selector:
    app: app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

