apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-web-app-deployment
  labels:
    app: fitness-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-web-app
  template:
    metadata:
      labels:
        app: fitness-web-app
    spec:
      containers:
        - name: fitness-web-app
          image: ahmedabduelkhaleq/fitness-web-app:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-web-app-service
spec:
  selector:
    app: fitness-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

