---
- name: Install kubectl
  hosts: all
  become: yes
  tasks:
    - name: Get latest stable kubectl version
      shell: |
        curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
      register: kubectl_version
      changed_when: false

    - name: Download kubectl binary
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"
        validate_certs: yes

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_check
      changed_when: false

    - name: Display kubectl version
      debug:
        msg: "kubectl installed successfully: {{ kubectl_check.stdout_lines | join('\n') }}"
