---
- name: Install Minikube on Ubuntu
  hosts: minikube_host
  become: true

  vars:
    kubectl_version: "v1.30.0"
    minikube_version: "v1.32.0"

  tasks:

    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - conntrack
          - virtualbox
          - virtualbox-ext-pack
        state: present

    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Download Minikube
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Rename minikube binary
      command: mv /usr/local/bin/minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Start Minikube
      become: false
      shell: |
        newgrp docker <<EONG
        minikube start --driver=docker
        EONG
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

