name: Trigger Jenkins Pipeline

on:
    pull_request:
      types: [closed]  # Trigger the workflow when the PR is closed (merged or declined)

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check if PR is merged
      if: github.event.pull_request.merged == true  # Only trigger if the PR is merged
      run: |
        curl -X POST "https://178c-197-35-155-98.ngrok-free.app/job/${{ secrets.JENKINS_JOB_NAME }}/build?token=${{ secrets.JENKINS_TOKEN }}" \
        --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
