name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you prefer

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Trigger Jenkins Job
      run: |
        curl -X POST "https://5bc8-197-35-71-163.ngrok-free.app/job/${{ secrets.JENKINS_JOB_NAME }}/build?token=${{ secrets.JENKINS_TOKEN }}" \
        --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
